version: '3.1'

services:

  postgres:
    image: postgis/postgis
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
